Engine["Enums"].Vehicles = {
    Events = {
        RequestProperties = "vehicles:RequestProperties",
        ReceiveProperties = "vehicles:ReceiveProperties",
        SetProperties = "vehicles:SetProperties",
        OnPropertiesUpdate = "vehicles:OnPropertiesUpdate",
        EnteringVehicle = "vehicles:EnteringVehicle",
        LeftVehicle = "vehicles:PlayerLeftVehicle",
        SwitchVehicleSeat = "vehicles:SwitchVehicleSeat",
        PlayerEnteredVehicle = "vehicles:PlayerEnteredVehicle",
        PlayerEnteredStreetVehicle = "vehicles:PlayerEnteredStreetVehicle",
        RequestSeat = "vehicles:RequestSeat",
        ReceiveSeat = "vehicles:ReceiveSeat"
    },
    
    Customisation = {
        modSpoiler = 0,
        modFrontBumper = 1,
        modRearBumper = 2,
        modSideSkirt = 3,
        modExhaust = 4,
        modChassis = 5,
        modGrill = 6,
        modHood = 7,
        modFender = 8,
        modRightFender = 9,
        modRoof = 10,
        modEngine = 11,
        modBrakes = 12,
        modTransmission = 13,
        modHorn = 14,
        modSuspension = 15,
        modArmor = 16,
        modNitrous = 17,
        modTurbo = 18,
        modSubwoofer = 19,
        modTyreSmoke = 20,
        modHydraulics = 21,
        modXenon = 22,
        modFrontWheels = 23,
        modBackWheels = 24,
        modPlateHolder = 25,
        modVanityPlate = 26,
        modTrimA = 27,
        modOrnaments = 28,
        modDashboard = 29,
        modDial = 30,
        modDoorSpeaker = 31,
        modSeats = 32,
        modSteeringWheel = 33,
        modShifterLeavers = 34,
        modAPlate = 35,
        modSpeakers = 36,
        modTrunk = 37,
        modHydrolic = 38,
        modEngineBlock = 39,
        modAirFilter = 40,
        modStruts = 41,
        modArchCover = 42,
        modAerials = 43,
        modTrimB = 44,
        modTank = 45,
        modWindows = 46,
        modDoorR = 47,
        modLivery = 48,
        modLightbar = 49
    },

    Horn = {
        [0] = "Klaxon de Camion",
        [1] = "Klaxon de Police",
        [2] = "Klaxon de Clown",
        [3] = "Klaxon Musical 1",
        [4] = "Klaxon Musical 2",
        [5] = "Klaxon Musical 3",
        [6] = "Klaxon Musical 4",
        [7] = "Klaxon Musical 5",
        [8] = "Klaxon Trombone Triste",
        [9] = "Klaxon Classique 1",
        [10] = "Klaxon Classique 2",
        [11] = "Klaxon Classique 3",
        [12] = "Klaxon Classique 4",
        [13] = "Klaxon Classique 5",
        [14] = "Klaxon Classique 6",
        [15] = "Klaxon Classique 7",
        [16] = "Klaxon Do",
        [17] = "Klaxon Ré",
        [18] = "Klaxon Mi",
        [19] = "Klaxon Fa",
        [20] = "Klaxon Sol",
        [21] = "Klaxon La",
        [22] = "Klaxon Si",
        [23] = "Klaxon Do Haut",
        [24] = "Klaxon Jazz 1",
        [25] = "Klaxon Jazz 2",
        [26] = "Klaxon Jazz 3",
        [27] = "Klaxon Jazz Boucle",
        [28] = "Klaxon Starspangban 1",
        [29] = "Klaxon Starspangban 2",
        [30] = "Klaxon Starspangban 3",
        [31] = "Klaxon Starspangban 4",
        [32] = "Klaxon Classique Boucle 1",
        [33] = "Klaxon Classique 8",
        [34] = "Klaxon Classique Boucle 2"
    },

    XenonColor = {
        [1] = {label = "Bleu", value = 1},
        [2] = {label = "Bleu Électrique", value = 2},
        [3] = {label = "Vert Menthe", value = 3},
        [4] = {label = "Vert Lime", value = 4},
        [5] = {label = "Jaune Vif", value = 5},
        [6] = {label = "Jaune", value = 6},
        [7] = {label = "Orange", value = 7},
        [8] = {label = "Rouge", value = 8},
        [9] = {label = "Rose Bois", value = 9},
        [10] = {label = "Rose Vif", value = 10},
        [11] = {label = "Violet", value = 11},
        [12] = {label = "Lumière Noire", value = 12}
    },

    NeonSupportType = {
        [1] = {label = "Avant", left = false, right = false, front = true, back = false},
        [2] = {label = "Arrière", left = false, right = false, front = false, back = true},
        [3] = {label = "Côtés", left = true, right = true, front = false, back = false},
        [4] = {label = "Avant et arrière", left = false, right = false, front = true, back = true},
        [5] = {label = "Avant et côtés", left = true, right = true, front = true, back = false},
        [6] = {label = "Arrière et côtés", left = true, right = true, front = false, back = true},
        [7] = {label = "Avant, arrière et côtés", left = true, right = true, front = true, back = true}
    },

    NeonColor = {
        [1] = {label = "Blanc", red = 255, green = 255, blue = 255},
        [2] = {label = "Bleu", red = 2, green = 21, blue = 255},
        [3] = {label = "Bleu Électrique", red = 3, green = 83, blue = 255},
        [4] = {label = "Vert Menthe", red = 0, green = 255, blue = 140},
        [5] = {label = "Vert Lime", red = 94, green = 255, blue = 2},
        [6] = {label = "Jaune", red = 255, green = 255, blue = 0},
        [7] = {label = "Fièvre Jaune", red = 255, green = 150, blue = 0},
        [8] = {label = "Rouge", red = 255, green = 0, blue = 128},
        [9] = {label = "Rose Bois", red = 255, green = 58, blue = 188},
        [10] = {label = "Rose Vif", red = 255, green = 5, blue = 195},
        [11] = {label = "Violet", red = 35, green = 1, blue = 255},
        [12] = {label = "Lumière Noire", red = 15, green = 3, blue = 255}
    },

    PlateType = {
        [1] = {label = "Bleu sur blanc 1", value = 0},
        [2] = {label = "Bleu sur blanc 2", value = 3},
        [3] = {label = "Bleu sur blanc 3", value = 4},
        [4] = {label = "Jaune sur bleu", value = 2},
        [5] = {label = "Jaune sur noir", value = 1}
    },

    ClassicColor = {
        ["Noir"] = 0,
        ["Noir Carbone"] = 147,
        ["Graphite"] = 1,
        ["Noir Anthracite"] = 11,
        ["Acier Noir"] = 2,
        ["Acier Foncé"] = 3,
        ["Argent"] = 4,
        ["Argent Bleuâtre"] = 5,
        ["Acier Laminé"] = 6,
        ["Argent Ombre"] = 7,
        ["Argent Pierre"] = 8,
        ["Argent Minuit"] = 9,
        ["Argent Fonte"] = 10,
        ["Rouge"] = 27,
        ["Rouge Torino"] = 28,
        ["Rouge Formule"] = 29,
        ["Rouge Lave"] = 150,
        ["Rouge Flamme"] = 30,
        ["Rouge Grâce"] = 31,
        ["Rouge Grenat"] = 32,
        ["Rouge Crépuscule"] = 33,
        ["Rouge Cabernet"] = 34,
        ["Rouge Vin"] = 143,
        ["Rouge Bonbon"] = 35,
        ["Rose Fuchsia"] = 135,
        ["Rose Pfsiter"] = 137,
        ["Rose Saumon"] = 136,
        ["Orange Lever du Soleil"] = 36,
        ["Orange"] = 38,
        ["Orange Brillant"] = 138,
        ["Or"] = 99,
        ["Bronze"] = 90,
        ["Jaune"] = 88,
        ["Jaune Course"] = 89,
        ["Jaune Rosée"] = 91,
        ["Vert Foncé"] = 49,
        ["Vert de Course"] = 50,
        ["Vert Mer"] = 51,
        ["Vert Olive"] = 52,
        ["Vert Brillant"] = 53,
        ["Vert Essence"] = 54,
        ["Vert Citron"] = 92,
        ["Bleu Minuit"] = 141,
        ["Bleu Galaxie"] = 61,
        ["Bleu Foncé"] = 62,
        ["Bleu Saxon"] = 63,
        ["Bleu"] = 64,
        ["Bleu Marin"] = 65,
        ["Bleu Port"] = 66,
        ["Bleu Diamant"] = 67,
        ["Bleu Surf"] = 68,
        ["Bleu Nautique"] = 69,
        ["Bleu Course"] = 73,
        ["Bleu Ultra"] = 70,
        ["Bleu Clair"] = 74,
        ["Marron Chocolat"] = 96,
        ["Marron Bison"] = 101,
        ["Marron Créen"] = 95,
        ["Marron Feltzer"] = 94,
        ["Marron Érable"] = 97,
        ["Marron Bois de Hêtre"] = 103,
        ["Marron Sienne"] = 104,
        ["Marron Selle"] = 98,
        ["Marron Mousse"] = 100,
        ["Marron Bois"] = 102,
        ["Marron Sable"] = 105,
        ["Marron Éclairci"] = 106,
        ["Violet Schafter"] = 71,
        ["Violet Spinnaker"] = 72,
        ["Violet Minuit"] = 142,
        ["Violet Brillant"] = 145,
        ["Crème"] = 107,
        ["Blanc Glacé"] = 111,
        ["Blanc Gel"] = 112
    },

    MatColor = {
        ["Noir"] = 12,
        ["Gris"] = 13,
        ["Gris Clair"] = 14,
        ["Blanc Glacé"] = 131,
        ["Bleu"] = 83,
        ["Bleu Foncé"] = 82,
        ["Bleu Minuit"] = 84,
        ["Violet Minuit"] = 149,
        ["Violet Schafter"] = 148,
        ["Rouge"] = 39,
        ["Rouge Foncé"] = 40,
        ["Orange"] = 41,
        ["Jaune"] = 42,
        ["Vert Citron"] = 55,
        ["Vert"] = 128,
        ["Vert Forêt"] = 151,
        ["Vert Feuillage"] = 155,
        ["Vert Olive"] = 152,
        ["Terre Foncée"] = 153,
        ["Beige Désert"] = 154
    },
    
    MetalsColor = {
        ["Acier Brossé"] = 117,
        ["Acier Noir Brossé"] = 118,
        ["Aluminium Brossé"] = 119,
        ["Or Pur"] = 158,
        ["Or Brossé"] = 159
    },

    HighEndWheels = {
        {name = "Shadow", id = 0},
        {name = "Hyper", id = 1},
        {name = "Blade", id = 2},
        {name = "Diamond", id = 3},
        {name = "Supa Gee", id = 4},
        {name = "Chromatic Z", id = 5},
        {name = "Mercie Ch.Lip", id = 6},
        {name = "Obey RS", id = 7},
        {name = "GT Chrome", id = 8},
        {name = "Cheetah R", id = 9},
        {name = "Solar", id = 10},
        {name = "Split Ten", id = 11},
        {name = "Dash VIP", id = 12},
        {name = "LozSpeed Ten", id = 13},
        {name = "Carbon Inferno", id = 14},
        {name = "Carbon Shadow", id = 15},
        {name = "Carbonic Z", id = 16},
        {name = "Carbon Solar", id = 17},
        {name = "Cheetah Carbon R", id = 18},
        {name = "Carbon S Racer", id = 19}
    },

    LowriderWheels = {
        {name = "Flare", id = 0},
        {name = "Wired", id = 1},
        {name = "Triple Golds", id = 2},
        {name = "Big Worm", id = 3},
        {name = "Seven Fives", id = 4},
        {name = "Split Six", id = 5},
        {name = "Fresh Mesh", id = 6},
        {name = "Lead Sled", id = 7},
        {name = "Turbine", id = 8},
        {name = "Super Fin", id = 9},
        {name = "Classic Rod", id = 10},
        {name = "Dollar", id = 11},
        {name = "Dukes", id = 12},
        {name = "Low Five", id = 13},
        {name = "Gooch", id = 14}
    },

    MuscleCarWheels = {
        {name = "Classic Five", id = 0},
        {name = "Dukes", id = 1},
        {name = "Muscle Freak", id = 2},
        {name = "Kracka", id = 3},
        {name = "Azreal", id = 4},
        {name = "Mecha", id = 5},
        {name = "Black Top", id = 6},
        {name = "Drag SPL", id = 7},
        {name = "Revolver", id = 8},
        {name = "Classic Rod", id = 9},
        {name = "Fairlie", id = 10},
        {name = "Spooner", id = 11},
        {name = "Five Star", id = 12},
        {name = "Old School", id = 13},
        {name = "El Jefe", id = 14},
        {name = "Dodman", id = 15},
        {name = "Six Gun", id = 16},
        {name = "Mercenary", id = 17}
    },

    OffRoadWheels = {
        {name = "Raider", id = 1},
        {name = "Mudslinger", id = 2},
        {name = "Nevis", id = 3},
        {name = "Cairngorm", id = 4},
        {name = "Amazon", id = 5},
        {name = "Challenger", id = 6},
        {name = "Dune Basher", id = 7},
        {name = "Five Star", id = 8},
        {name = "Rock Crawler", id = 9},
        {name = "Mill Spec Steelie", id = 10}
    },

    SportWheels = {    
        {name = "Inferno", id = 0},
        {name = "Deep Five", id = 1},
        {name = "Lozspeed Mk.V", id = 2},
        {name = "Diamond Cut", id = 3},
        {name = "Chrono", id = 4},
        {name = "Feroci RR", id = 5},
        {name = "FiftyNine", id = 6},
        {name = "Mercie", id = 7},
        {name = "Synthetic Z", id = 8},
        {name = "Organic Type 0", id = 9},
        {name = "Endo v.1", id = 10},
        {name = "GT One", id = 11},
        {name = "Duper 7", id = 12},
        {name = "Uzer", id = 13},
        {name = "GroundRide", id = 14},
        {name = "S Racer", id = 15},
        {name = "Venum", id = 16},
        {name = "Cosmo", id = 17},
        {name = "Dash VIP", id = 18},
        {name = "Ice Kid", id = 19},
        {name = "Ruff Weld", id = 20},
        {name = "Wangan Master", id = 21},
        {name = "Super Five", id = 22},
        {name = "Endo v.2", id = 23},
        {name = "Split Six", id = 24}
    },

    SuvWheels = {
        {name = "VIP", id = 0},
        {name = "Benefactor", id = 1},
        {name = "Cosmo", id = 2},
        {name = "Bippu", id = 3},
        {name = "Royalsix", id = 4},
        {name = "Fagorme", id = 5},
        {name = "Deluxe", id = 6},
        {name = "Iced Out", id = 7},
        {name = "Cognoscenti", id = 8},
        {name = "Lozspeed Ten", id = 9},
        {name = "Supernova", id = 10},
        {name = "Obey RS", id = 11},
        {name = "Lozspeed Baller", id = 12},
        {name = "Extravaganzo", id = 13},
        {name = "Splitsix", id = 14},
        {name = "Empowered", id = 15},
        {name = "Dash VIP", id = 16},
        {name = "Cutter", id = 17}
    },

    TunningWheels = {
        {name = "Cosmo", id = 0},
        {name = "Supermesh", id = 1},
        {name = "Outsider", id = 2},
        {name = "Rollas", id = 3},
        {name = "Driftmeister", id = 4},
        {name = "Slicer", id = 5},
        {name = "El Quatro", id = 6},
        {name = "Dubbed", id = 7},
        {name = "Fivestar", id = 8},
        {name = "Slideways", id = 9},
        {name = "Apex", id = 10},
        {name = "Stanced EG", id = 11},
        {name = "Countersteer", id = 12},
        {name = "Endo V1", id = 12},
        {name = "Endo V2 Dish", id = 13},
        {name = "Gruppe Z", id = 14},
        {name = "Choku Dori", id = 15},
        {name = "Chicane", id = 16},
        {name = "Saisoku", id = 17},
        {name = "Dished Eight", id = 18},
        {name = "Fujiwara", id = 19},
        {name = "Zokusha", id = 20},
        {name = "Battle VIII", id = 21},
        {name = "Rally Master", id = 22}
    },

    StreetWheels = {
        {name = "Retro Steelie", id = 0},
        {name = "Poverty Spec Steelie", id = 1},
        {name = "Concave Steelie", id = 2},
        {name = "Nebula", id = 3},
        {name = "Hotring Streelie", id = 4},
        {name = "Cup Champion", id = 5},
        {name = "Stancedd EG Custom", id = 6},
        {name = "Kracka Custom", id = 7},
        {name = "Dukes Custom", id = 8},
        {name = "Endo V3 Custom", id = 9},
        {name = "V8 Killer", id = 10},
        {name = "Fujiwara Custom", id = 11},
        {name = "Cosmo MKII", id = 12},
        {name = "Aero Star", id = 13}
    },

    TrackWheels = {
        {name = "Rally Throwback", id = 0},
        {name = "Gravel Trap", id = 1},
        {name = "Stove Top", id = 2},
        {name = "Stove Top Mesh", id = 3},
        {name = "Retro 3 Piece", id = 4},
        {name = "Rally Monoblock", id = 5},
        {name = "Forged 5", id = 6},
        {name = "Split Star", id = 7},
        {name = "Speed Boy", id = 8},
        {name = "90S Running", id = 9},
        {name = "Tropos", id = 10},
        {name = "Exos", id = 11},
        {name = "Hiht Five", id = 12},
        {name = "Super Luxe", id = 13},
        {name = "Pure Business", id = 14},
        {name = "Pepper Pot", id = 15},
        {name = "Bloackstop Blender", id = 16},
        {name = "Throwback", id = 17},
        {name = "Expressway", id = 18},
        {name = "Hidden Six", id = 19},
        {name = "Dinka SPL", id = 20},
        {name = "Retro Turbofan", id = 21},
        {name = "Conical Turbofan", id = 22},
        {name = "Ice Storm", id = 23},
        {name = "Super Turbine", id = 24},
        {name = "Modern Mesh", id = 25},
        {name = "Forget Star", id = 26},
        {name = "Snowkflake", id = 27},
        {name = "Giga Mesh", id = 28},
        {name = "Mesh Meister", id = 29}
    },

    WheelsFumes = {
        ["Noir"] = {1, 1, 1},
        ["Rouge"] = {255, 0, 0},
        ["Orange"] = {255, 127, 0},
        ["Jaune"] = {255, 255, 0},
        ["Vert"] = {0, 255, 0},
        ["Bleu"] = {0, 0, 255},
        ["Violet"] = {153, 0, 153},
        ["Rose"] = {255, 0, 255},
        ["Gris"] = {128, 128, 128},
        ["Bleu clair"] = {0, 255, 255},
        ["Vert Lime"] = {50, 205, 50},
        ["Marron"] = {139, 69, 19},
        ["Or"] = {255, 215, 0}
    },

    WindowColor = {
        [1] = {label = "Fumé clair", value = 3},
        [2] = {label = "Fumé foncé", value = 2},
        [3] = {label = "Limousine", value = 1}
    },

    BrakeType = {
        [1] = {label = "Freins de rue", value = 0},
        [2] = {label = "Freins de sport", value = 1},
        [3] = {label = "Freins de course", value = 2}
    },
    
    EngineType = {
        [1] = {label = "Reprog moteur Niv. 2", value = 0},
        [2] = {label = "Reprog moteur Niv. 3", value = 1},
        [3] = {label = "Reprog moteur Niv. 4", value = 2}
    },

    SuspensionType = {
        [1] = {label = "Suspension de rue", value = 0},
        [2] = {label = "Suspension de sport", value = 1},
        [3] = {label = "Suspension de course", value = 2}
    },

    TransmissionType = {
        [1] = {label = "Transmission de rue", value = 0},
        [2] = {label = "Transmission de sport", value = 1},
        [3] = {label = "Transmission de course", value = 2}
    },

    Classes = {
        [0] = "compacts",
        [1] = "sedans",
        [2] = "suvs",
        [3] = "coupes",
        [4] = "muscle",
        [5] = "sports_classics",
        [6] = "sports",
        [7] = "super",
        [8] = "motorcycles",
        [9] = "offroad",
        [10] = "industrial",
        [11] = "utility",
        [12] = "vans",
        [13] = "cycles",
        [14] = "boats",
        [15] = "helicopters",
        [16] = "planes",
        [17] = "service",
        [18] = "emergency",
        [19] = "military",
        [20] = "commercial",
        [21] = "trains",
        [22] = "open_wheel"
    }
    
};