Engine["Enums"].Shop = {
    Events = {
        requestHistory = "shop:requestHistory",
        receiveHistory = "shop:receiveHistory",
        requestCoins = "shop:requestCoins",
        receiveCoins = "shop:receiveCoins",
        changeBucket = "shop:changeBucket",
        setLastPosition = "shop:setLastPosition",
        deleteLastPosition = "shop:deleteLastPosition",
        buyVehicle = "shop:buyVehicle",
        requestLimitedVehicles = "shop:requestLimitedVehicles",
        receiveLimitedVehicles = "shop:receiveLimitedVehicles",
        buyLimitedVehicle = "shop:buyLimitedVehicle",
        receiveLimitedCommand = "shop:receiveLimitedCommand",
        addLimitedVehicle = "shop:addLimitedVehicle",
        buyMysteryBox = "shop:buyMysteryBox",
        receiveMysteryReward = "shop:receiveMysteryReward",
        startAnimationMystery = "shop:startAnimationMystery",
        acceptMysteryReward = "shop:acceptMysteryReward",
        refundMysteryReward = "shop:refundMysteryReward",
        buyPackage = "shop:buyPackage",
        buyWeapon = "shop:buyWeapon",
        buyExWeapon = "shop:buyExWeapon",
    },
}