sAdmin = {}
sAdmin.Config = {
    DefaultGroup = "user",
    KeyOpenMenu = "F9",
    KeyNoclip = "F10",
    KeyTPMarker = "F11",
    Debug = false,
    Print = {
        DefaultPrefix = "[^4sAdmin^7]",
        DebugPrefix = "[^4sAdmin^7][^3Debug^7]"
    },
    JailPos = vector3(2045.73, -3887.56, 1.25),
    TrollClothes = {
        TrollPreset = {
            male = {
                ['tshirt_1'] = 15, ['tshirt_2'] = 0,
                ['torso_1'] = 397, ['torso_2'] = 0,
                ['decals_1'] = 0, ['decals_2'] = 0,
                ['arms'] = 197,
                ['pants_1'] = 145, ['pants_2'] = 0,
                ['shoes_1'] = 33, ['shoes_2'] = 0,
                ['helmet_1'] = -1, ['helmet_2'] = 0,
                ['mask_1'] = 147, ['mask_2'] = 0,
                ['bag_1'] = 0, ['bag_2'] = 0,
                ['chain_1'] = 0, ['chain_2'] = 0,
                ['ears_1'] = -1, ['ears_2'] = 0,
            },
            female = {
                ['tshirt_1'] = 15, ['tshirt_2'] = 0,
                ['torso_1'] = 397, ['torso_2'] = 0,
                ['decals_1'] = 0, ['decals_2'] = 0,
                ['arms'] = 197,
                ['pants_1'] = 145, ['pants_2'] = 9,
                ['shoes_1'] = 33, ['shoes_2'] = 0,
                ['helmet_1'] = -1, ['helmet_2'] = 0,
                ['mask_1'] = 147, ['mask_2'] = 0,
                ['bag_1'] = 0, ['bag_2'] = 0,
                ['chain_1'] = 0, ['chain_2'] = 0,
                ['ears_1'] = -1, ['ears_2'] = 0,
            },
        },
    },
    Perms = {
        AccesCat = {
            ["interactBoard"] = {
                ["friends"] = false,
                -- ["animateur"] = false,
                ["helpeur"] = false,
                ["moderateur"] = false,
                ["admin"] = true,
                ["responsable"] = true,
                ["gerantstaff"] = true,
                ["fondateur"] = true,
            },
            ["interaction_perso"] = {
                ["friends"] = true,
                -- ["animateur"] = true,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true, 
                ["responsable"] = true,
                ["gerantstaff"] = true,
                ["fondateur"] = true,
            },
            ["interaction_vehicle"] ={
                ["friends"] = true,
                -- ["animateur"] = true,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true, 
                ["responsable"] = true,
                ["gerantstaff"] = true,
                ["fondateur"] = true,
            },
            ["report_menu"] = {
                ["friends"] = true,
                -- ["animateur"] = false,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true,
                ["responsable"] = true, 
                ["gerantstaff"] = true,
                ["fondateur"] = true,
            },
            ["interaction_players"] = {
                ["friends"] = true,
                -- ["animateur"] = true,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true,
                ["responsable"] = true,
                ["gerantstaff"] = true,
                ["fondateur"] = true,
            },
            ["interaction_cardinal"] = {
                ["friends"] = false,
                -- ["animateur"] = false,
                ["helpeur"] = false,
                ["moderateur"] = false,
                ["admin"] = false,
                ["responsable"] = true,
                ["gerantstaff"] = true,
                ["fondateur"] = true,
            },
            ['show_staffList'] = {
                ["friends"] = false,
                -- ["animateur"] = false,
                ["helpeur"] = false,
                ["moderateur"] = false,
                ["admin"] = false,
                ["responsable"] = false,
                ["gerantstaff"] = true,
                ["fondateur"] = true,
            },
            ["personnal_gestion_2"] = {
                ["friends"] = false,
                -- ["animateur"] = false,
                ["helpeur"] = false,
                ["moderateur"] = false,
                ["admin"] = true, 
                ["responsable"] = true,
                ["gerantstaff"] = true,
                ["fondateur"] = true,   
            }
        },
        Buttons = {
            ["cat_persoMenu"] = {
                ["reset_identity"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,   
                },
                ["noclip"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["show_gamertags"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["show_staffInfo"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["use_pistol_mode"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["giveMoney"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false,
                    ["responsable"] = true, 
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,   
                },
                ["teleport_waypoint"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true, 
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                }
            },
            ["cat_vehMenu"] = {
                ["repairVehicle"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                    ["responsable"] = true, 
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["clearVehicle"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["upgradeVehicules"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
            },
            ["cat_playersActions"] = {
                ["skin"] = {
                    ["friends"] = true,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["goto"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["wipe"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["bring"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["tpparkingcentral"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["freeze"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["sendMess"] = {
                    ["friends"] = false,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["spec"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,                  
                    ["fondateur"] = true,
                },
                ["revive"] = {
                    ["friends"] = true,
                    -- ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,                   
                    ["fondateur"] = true,
                },
                ["kick"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,                   
                    ["fondateur"] = true,
                },
                ["ban"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,                  
                    ["fondateur"] = true,
                },
                ["showInventory"] = {
                    ["friends"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["giveMoney"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["clearLoadout"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
            },
            ["cat_cardinalActions"] = {
                ["peds"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = false,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["resetPeds"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["giveVehicle"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = false,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["deleteReport"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = false,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["gang"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                },
                ["event"] = {
                    ["friends"] = false,
                    -- ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = false, 
                    ["responsable"] = true,
                    ["gerantstaff"] = true,
                    ["fondateur"] = true,
                }
            }
        }
    }
}