Config = {}
Config.Locale = 'fr'

Config.DefaultGroup = 'user'
Config.DefaultLevel = '0'
Config.CommandPrefix = '/'
Config.DefaultPosition = vector3(-666.22, 581.5, 140.57)
Config.DefaultIdentifier = "license";

Config.Accounts = {
	['cash'] = {
		label = _U('cash'),
		starting = 0,
		priority = 1
	},
	['dirtycash'] = {
		label = _U('dirtycash'),
		starting = 0,
		priority = 2
	},
	['bank'] = {
		label = _U('bank'),
		starting = 0,
		priority = 3
	},
	['crypto'] = {
		label = 'Crypto',
		starting = 0,
		priority = 4
	},
	['chip'] = {
		label = 'Jetons Casino',
		starting = 0,
		priority = 4
	}
}

Config.EnableSocietyPayouts = true
Config.PaycheckInterval = 45 * 60 * 1000
Config.MaxWeight = 50

Config["Environement"] 									= {}
Config["Environement"]["DisableHealthRegeneration"]  	= true
Config["Environement"]["DisableVehicleRewards"]      	= true
Config["Environement"]["DisableWeaponWheel"]         	= true
Config["Environement"]["DisableNPCDrops"]            	= true
Config["Environement"]["DisableAimAssist"]            	= true
Config["Environement"]["DisableDispatchServices"]       = true
Config["Environement"]["DisableScenarios"]            	= true
Config["Environement"]["EnableWantedLevel"]            	= true
Config["Environement"]["RemoveHudCommonents"] = {
	[1] = true, --WANTED_STARS,
	[2] = false, --WEAPON_ICON
	[3] = true, --CASH
	[4] = true,  --MP_CASH
	[5] = false, --MP_MESSAGE
	[6] = false, --VEHICLE_NAME
	[7] = false,-- AREA_NAME
	[8] = false,-- VEHICLE_CLASS
	[9] = false, --STREET_NAME
	[10] = false, --HELP_TEXT
	[11] = false, --FLOATING_HELP_TEXT_1
	[12] = false, --FLOATING_HELP_TEXT_2
	[13] = true, --CASH_CHANGE
	[14] = false, --RETICLE
	[15] = false, --SUBTITLE_TEXT
	[16] = false, --RADIO_STATIONS
	[17] = false, --SAVING_GAME,
	[18] = false, --GAME_STREAM
	[19] = true, --WEAPON_WHEEL
	[20] = true, --WEAPON_WHEEL_STATS
	[21] = false, --HUD_COMPONENTS
	[22] = true, --HUD_WEAPONS

};

Config.PickupWeapons = {
	"PICKUP_WEAPON_BULLPUPSHOTGUN",
	"PICKUP_WEAPON_ASSAULTSMG",
	"PICKUP_VEHICLE_WEAPON_ASSAULTSMG",
	"PICKUP_WEAPON_PISTOL50",
	"PICKUP_VEHICLE_WEAPON_PISTOL50",
	"PICKUP_AMMO_BULLET_MP",
	"PICKUP_AMMO_MISSILE_MP",
	"PICKUP_AMMO_GRENADELAUNCHER_MP",
	"PICKUP_WEAPON_ASSAULTRIFLE",
	"PICKUP_WEAPON_CARBINERIFLE",
	"PICKUP_WEAPON_ADVANCEDRIFLE",
	"PICKUP_WEAPON_MG",
	"PICKUP_WEAPON_COMBATMG",
	"PICKUP_WEAPON_SNIPERRIFLE",
	"PICKUP_WEAPON_HEAVYSNIPER",
	"PICKUP_WEAPON_MICROSMG",
	"PICKUP_WEAPON_SMG",
	"PICKUP_ARMOUR_STANDARD",
	"PICKUP_WEAPON_RPG",
	"PICKUP_WEAPON_MINIGUN",
	"PICKUP_HEALTH_STANDARD",
	"PICKUP_WEAPON_PUMPSHOTGUN",
	"PICKUP_WEAPON_SAWNOFFSHOTGUN",
	"PICKUP_WEAPON_ASSAULTSHOTGUN",
	"PICKUP_WEAPON_GRENADE",
	"PICKUP_WEAPON_MOLOTOV",
	"PICKUP_WEAPON_SMOKEGRENADE",
	"PICKUP_WEAPON_STICKYBOMB",
	"PICKUP_WEAPON_PISTOL",
	"PICKUP_WEAPON_COMBATPISTOL",
	"PICKUP_WEAPON_APPISTOL",
	"PICKUP_WEAPON_GRENADELAUNCHER",
	"PICKUP_MONEY_VARIABLE",
	"PICKUP_GANG_ATTACK_MONEY",
	"PICKUP_WEAPON_STUNGUN",
	"PICKUP_WEAPON_PETROLCAN",
	"PICKUP_WEAPON_KNIFE",
	"PICKUP_WEAPON_NIGHTSTICK",
	"PICKUP_WEAPON_HAMMER",
	"PICKUP_WEAPON_BAT",
	"PICKUP_WEAPON_GolfClub",
	"PICKUP_WEAPON_CROWBAR",
	"PICKUP_CUSTOM_SCRIPT",
	"PICKUP_CAMERA",
	"PICKUP_PORTABLE_PACKAGE",
	"PICKUP_PORTABLE_CRATE_UNFIXED",
	"PICKUP_PORTABLE_PACKAGE_LARGE_RADIUS",
	"PICKUP_PORTABLE_FM_CONTENT_MISSION_ENTITY_SMALL",
	"PICKUP_PORTABLE_CRATE_UNFIXED_INCAR",
	"PICKUP_PORTABLE_CRATE_UNFIXED_INAIRVEHICLE_WITH_PASSENGERS",
	"PICKUP_PORTABLE_CRATE_UNFIXED_INAIRVEHICLE_WITH_PASSENGERS_UPRIGHT",
	"PICKUP_PORTABLE_CRATE_UNFIXED_INCAR_WITH_PASSENGERS",
	"PICKUP_PORTABLE_CRATE_FIXED_INCAR_WITH_PASSENGERS",
	"PICKUP_PORTABLE_CRATE_FIXED_INCAR_SMALL",
	"PICKUP_PORTABLE_CRATE_UNFIXED_INCAR_SMALL",
	"PICKUP_PORTABLE_CRATE_UNFIXED_LOW_GLOW",
	"PICKUP_MONEY_CASE",
	"PICKUP_MONEY_WALLET",
	"PICKUP_MONEY_PURSE",
	"PICKUP_MONEY_DEP_BAG",
	"PICKUP_MONEY_MED_BAG",
	"PICKUP_MONEY_PAPER_BAG",
	"PICKUP_MONEY_SECURITY_CASE",
	"PICKUP_VEHICLE_WEAPON_COMBATPISTOL",
	"PICKUP_VEHICLE_WEAPON_APPISTOL",
	"PICKUP_VEHICLE_WEAPON_PISTOL",
	"PICKUP_VEHICLE_WEAPON_GRENADE",
	"PICKUP_VEHICLE_WEAPON_MOLOTOV",
	"PICKUP_VEHICLE_WEAPON_SMOKEGRENADE",
	"PICKUP_VEHICLE_WEAPON_STICKYBOMB",
	"PICKUP_VEHICLE_HEALTH_STANDARD",
	"PICKUP_VEHICLE_HEALTH_STANDARD_LOW_GLOW",
	"PICKUP_VEHICLE_ARMOUR_STANDARD",
	"PICKUP_VEHICLE_WEAPON_MICROSMG",
	"PICKUP_VEHICLE_WEAPON_SMG",
	"PICKUP_VEHICLE_WEAPON_SAWNOFF",
	"PICKUP_VEHICLE_CUSTOM_SCRIPT",
	"PICKUP_VEHICLE_CUSTOM_SCRIPT_NO_ROTATE",
	"PICKUP_VEHICLE_CUSTOM_SCRIPT_LOW_GLOW",
	"PICKUP_VEHICLE_MONEY_VARIABLE",
	"PICKUP_SUBMARINE",
	"PICKUP_HEALTH_SNACK",
	"PICKUP_PARACHUTE",
	"PICKUP_AMMO_PISTOL",
	"PICKUP_AMMO_SMG",
	"PICKUP_AMMO_RIFLE",
	"PICKUP_AMMO_MG",
	"PICKUP_AMMO_SHOTGUN",
	"PICKUP_AMMO_SNIPER",
	"PICKUP_AMMO_GRENADELAUNCHER",
	"PICKUP_AMMO_RPG",
	"PICKUP_AMMO_MINIGUN",
	"PICKUP_WEAPON_BOTTLE",
	"PICKUP_WEAPON_SNSPISTOL",
	"PICKUP_WEAPON_HEAVYPISTOL",
	"PICKUP_WEAPON_SPECIALCARBINE",
	"PICKUP_WEAPON_BULLPUPRIFLE",
	"PICKUP_WEAPON_RAYPISTOL",
	"PICKUP_WEAPON_RAYCARBINE",
	"PICKUP_WEAPON_RAYMINIGUN",
	"PICKUP_WEAPON_PISTOLXM3",
	"PICKUP_WEAPON_CANDYCANE",
	"PICKUP_WEAPON_RAILGUNXM3",
	"PICKUP_WEAPON_PROXMINE",
	"PICKUP_WEAPON_HOMINGLAUNCHER",
	"PICKUP_AMMO_HOMINGLAUNCHER",
	"PICKUP_WEAPON_BULLPUPRIFLE_MK2",
	"PICKUP_WEAPON_DOUBLEACTION",
	"PICKUP_WEAPON_MARKSMANRIFLE_MK2",
	"PICKUP_WEAPON_PUMPSHOTGUN_MK2",
	"PICKUP_WEAPON_REVOLVER_MK2",
	"PICKUP_WEAPON_SNSPISTOL_MK2",
	"PICKUP_WEAPON_SPECIALCARBINE_MK2",
	"PICKUP_WEAPON_GUSENBERG",
	"PICKUP_WEAPON_DAGGER",
	"PICKUP_WEAPON_VINTAGEPISTOL",
	"PICKUP_WEAPON_FIREWORK",
	"PICKUP_WEAPON_MUSKET",
	"PICKUP_AMMO_FIREWORK",
	"PICKUP_AMMO_FIREWORK_MP",
	"PICKUP_PORTABLE_DLC_VEHICLE_PACKAGE",
	"PICKUP_WEAPON_HATCHET",
	"PICKUP_WEAPON_RAILGUN",
	"PICKUP_WEAPON_HEAVYSHOTGUN",
	"PICKUP_WEAPON_MARKSMANRIFLE",
	"PICKUP_WEAPON_COMBATSHOTGUN",
	"PICKUP_WEAPON_GADGETPISTOL",
	"PICKUP_WEAPON_MILITARYRIFLE",
	"PICKUP_WEAPON_FLAREGUN",
	"PICKUP_AMMO_FLAREGUN",
	"PICKUP_WEAPON_CERAMICPISTOL",
	"PICKUP_WEAPON_HAZARDCAN",
	"PICKUP_WEAPON_NAVYREVOLVER",
	"PICKUP_WEAPON_KNUCKLE",
	"PICKUP_WEAPON_MARKSMANPISTOL",
	"PICKUP_WEAPON_COMBATPDW",
	"PICKUP_PORTABLE_CRATE_FIXED_INCAR",
	"PICKUP_WEAPON_COMPACTRIFLE",
	"PICKUP_WEAPON_DBSHOTGUN",
	"PICKUP_WEAPON_MACHETE",
	"PICKUP_WEAPON_MACHINEPISTOL",
	"PICKUP_WEAPON_FLASHLIGHT",
	"PICKUP_WEAPON_REVOLVER",
	"PICKUP_WEAPON_SWITCHBLADE",
	"PICKUP_WEAPON_AUTOSHOTGUN",
	"PICKUP_WEAPON_BATTLEAXE",
	"PICKUP_WEAPON_COMPACTLAUNCHER",
	"PICKUP_WEAPON_MINISMG",
	"PICKUP_WEAPON_PIPEBOMB",
	"PICKUP_WEAPON_POOLCUE",
	"PICKUP_WEAPON_WRENCH",
	"PICKUP_WEAPON_ASSAULTRIFLE_MK2",
	"PICKUP_WEAPON_CARBINERIFLE_MK2",
	"PICKUP_WEAPON_COMBATMG_MK2",
	"PICKUP_WEAPON_HEAVYSNIPER_MK2",
	"PICKUP_WEAPON_PISTOL_MK2",
	"PICKUP_WEAPON_SMG_MK2",
	"PICKUP_WEAPON_STONE_HATCHET",
	"PICKUP_WEAPON_METALDETECTOR",
	"PICKUP_WEAPON_TACTICALRIFLE",
	"PICKUP_WEAPON_PRECISIONRIFLE",
	"PICKUP_WEAPON_EMPLAUNCHER",
	"PICKUP_AMMO_EMPLAUNCHER",
	"PICKUP_WEAPON_HEAVYRIFLE",
	"PICKUP_WEAPON_PETROLCAN_SMALL_RADIUS",
	"PICKUP_WEAPON_FERTILIZERCAN",
	"PICKUP_WEAPON_STUNGUN_MP",
	"PICKUP_WEAPON_TECPISTOL",
}

Config.BlacklistedVehicles = {
    
	'tug',
	'avisa',
	'dinghy5',
	'kosatka',
	'patrolboat',
	'cerberus',
	'deluxo',
	'cerberus2',
	'cerberus3',
	'hauler',
	'hauler2',
	'phantom2',
	'stockade3',
	'terbyte',
	'issi6',
	'issi5',
	'issi4',
	'riot2',
	'akula',
	'annihilator',
	'annihilator2',
	'buzzard',
	'cargobob',
	'cargobob2',
	'cargobob3',
	'cargobob4',
	'hunter',
	'savage',
	'skylift',
	'valkyrie',
	'valkyrie2',
	'bulldozer',
	'cutter',
	'dump',
	'handler',
	'apc',
	'barrage',
	'chernobog',
	'halftrack',
	'khanjali',
	'minitank',
	'rhino',
	'scarab',
	'scarab2',
	'scarab3',
	'thruster',
	'trailersmall2',
	'oppressor',
	'oppressor2',
	'blazer5',
	'schafter6',
	'schafter5',
	'baller5',
	'tampa3',
	'boxville5',
	'ruiner2',
	'bruiser',
	'bruiser2',
	'bruiser3',
	'brutus',
	'kuruma2',
	'brutus2',
	'brutus3',
	'dune3',
	'dune4',
	'dune5',
	'insurgent',
	'insurgent3',
	'marshall',
	'monster',
	'monster3',
	'monster4',
	'monster5',
	'menacer',
	'nightshark',
	'technical',
	'technical2',
	'technical3',
	'zhaba',
	'avenger',
	'avenger2',
	'besra',
	'blimp',
	'blimp2',
	'blimp3',
	'bombushka',
	'cargoplane',
	'hydra',
	'jet',
	'lazer',
	'molotok',
	'nokota',
	'pyro',
	'rogue',
	'starling',
	'strikeforce',
	'titan',
	'volatol',
	'alkonost',
	'baller6',
	'brickade',
	'rallytruck',
	'tourbus',
	'wastelander',
	'zr380',
	'zr3802',
	'zr3803',
	'toreador',
	'vigilante',
	'armytanker',
	'armytrailer',
	'armytrailer2',
	'baletrailer',
	'boattrailer',
	'cablecar',
	'docktrailer',
	'freighttrailer',
	'graintrailer',
	'proptrailer',
	'raketrailer',
	'tr2',
	'tr3',
	'tr4',
	'trflat',
	'tvtrailer',
	'tanker',
	'tanker2',
	'trailerlarge',
	'trailerlogs',
	'trailersmall',
	'trailers',
	'trailers2',
	'trailers3',
	'trailers4',
	'freight',
	'freightcar',
	'freightcont1',
	'freightcont2',
	'freightgrain',
	'metrotrain',
	'tankercar',
	'voltic2',
	'savestra',
	'limo2',
	'scramjet',
	'slamvan6',
	'slamvan5',
	'slamvan4',
	'imperator3',
	'duke2',
	'dominator6',
	'dominator5',
	'dominator4',
	'deathbike2',
	'deathbike3',
	'deathbike',
	'submersible2',
	'submersible',
	'firetruk',
	'mixer',
	'mixer2',
	'ruiner3',
	'tula',
	'rcbandito',
	'caracara',
	'buffalo4',
	'granger2',
	'champion',
	'paragon2',
	'deity',
	'jubilee',
	'stromberg',
	'havok',
	'Mogul',
	'patriot3',

};