---@param tbl table
---@param one number
---@param two number
---@param single? boolean
local function addVariation(tbl, one, two, single)
    if not single then
        tbl[one] = two
        tbl[two] = one
    else
        tbl[one] = two
    end
end

Variations = {
    Bag = {
        male = {},
        female = {}
    },
    Top = {
        male = {},
        female = {}
    },
    Visor = {
        male = {},
        female = {}
    },
    Hair = {
        male = {},
        female = {}
    },
    Gloves = {
        male = {},
        female = {}
    }
}

-- [[ BAGS (5) ]] --
-- MALE
addVariation(Variations.Bag.male, 45, 44)
addVariation(Variations.Bag.male, 41, 40)
-- FEMALE
addVariation(Variations.Bag.female, 45, 44)
addVariation(Variations.Bag.female, 41, 40)
-- [[ Top (11) ]] --
-- MALE
addVariation(Variations.Top.male, 29, 30)
addVariation(Variations.Top.male, 31, 32)
addVariation(Variations.Top.male, 42, 43)
addVariation(Variations.Top.male, 68, 69)
addVariation(Variations.Top.male, 74, 75)
addVariation(Variations.Top.male, 87, 88)
addVariation(Variations.Top.male, 99, 100)
addVariation(Variations.Top.male, 101, 102)
addVariation(Variations.Top.male, 103, 104)
addVariation(Variations.Top.male, 126, 127)
addVariation(Variations.Top.male, 129, 130)
addVariation(Variations.Top.male, 184, 185)
addVariation(Variations.Top.male, 188, 189)
addVariation(Variations.Top.male, 194, 195)
addVariation(Variations.Top.male, 196, 197)
addVariation(Variations.Top.male, 198, 199)
addVariation(Variations.Top.male, 200, 203)
addVariation(Variations.Top.male, 202, 205)
addVariation(Variations.Top.male, 206, 207)
addVariation(Variations.Top.male, 210, 211)
addVariation(Variations.Top.male, 217, 218)
addVariation(Variations.Top.male, 229, 230)
addVariation(Variations.Top.male, 232, 233)
addVariation(Variations.Top.male, 251, 253)
addVariation(Variations.Top.male, 256, 261)
addVariation(Variations.Top.male, 262, 263)
addVariation(Variations.Top.male, 265, 266)
addVariation(Variations.Top.male, 267, 268)
addVariation(Variations.Top.male, 279, 280)
addVariation(Variations.Top.male, 301, 302)
-- FEMALE
addVariation(Variations.Top.female, 53, 52)
addVariation(Variations.Top.female, 57, 58)
addVariation(Variations.Top.female, 62, 63)
addVariation(Variations.Top.female, 90, 91)
addVariation(Variations.Top.female, 92, 93)
addVariation(Variations.Top.female, 94, 95)
addVariation(Variations.Top.female, 187, 186)
addVariation(Variations.Top.female, 190, 191)
addVariation(Variations.Top.female, 196, 197)
addVariation(Variations.Top.female, 198, 199)
addVariation(Variations.Top.female, 200, 201)
addVariation(Variations.Top.female, 202, 205)
addVariation(Variations.Top.female, 204, 207)
addVariation(Variations.Top.female, 210, 211)
addVariation(Variations.Top.female, 214, 215)
addVariation(Variations.Top.female, 227, 228)
addVariation(Variations.Top.female, 239, 240)
addVariation(Variations.Top.female, 242, 243)
addVariation(Variations.Top.female, 259, 261)
addVariation(Variations.Top.female, 265, 270)
addVariation(Variations.Top.female, 271, 272)
addVariation(Variations.Top.female, 274, 275)
addVariation(Variations.Top.female, 276, 277)
addVariation(Variations.Top.female, 292, 293)
-- [[ Visor ]] --
-- MALE
addVariation(Variations.Visor.male, 9, 10)
addVariation(Variations.Visor.male, 18, 67)
addVariation(Variations.Visor.male, 82, 67)
addVariation(Variations.Visor.male, 44, 45)
addVariation(Variations.Visor.male, 50, 68)
addVariation(Variations.Visor.male, 51, 69)
addVariation(Variations.Visor.male, 52, 70)
addVariation(Variations.Visor.male, 53, 71)
addVariation(Variations.Visor.male, 62, 72)
addVariation(Variations.Visor.male, 65, 66)
addVariation(Variations.Visor.male, 73, 74)
addVariation(Variations.Visor.male, 76, 77)
addVariation(Variations.Visor.male, 79, 78)
addVariation(Variations.Visor.male, 80, 81)
addVariation(Variations.Visor.male, 91, 92)
addVariation(Variations.Visor.male, 104, 105)
addVariation(Variations.Visor.male, 109, 110)
addVariation(Variations.Visor.male, 116, 117)
addVariation(Variations.Visor.male, 118, 119)
addVariation(Variations.Visor.male, 123, 124)
addVariation(Variations.Visor.male, 125, 126)
addVariation(Variations.Visor.male, 127, 128)
addVariation(Variations.Visor.male, 130, 131)
-- FEMALE
addVariation(Variations.Visor.female, 43, 44)
addVariation(Variations.Visor.female, 49, 67)
addVariation(Variations.Visor.female, 64, 65)
addVariation(Variations.Visor.female, 65, 64)
addVariation(Variations.Visor.female, 51, 69)
addVariation(Variations.Visor.female, 50, 68)
addVariation(Variations.Visor.female, 52, 70)
addVariation(Variations.Visor.female, 62, 71)
addVariation(Variations.Visor.female, 72, 73)
addVariation(Variations.Visor.female, 75, 76)
addVariation(Variations.Visor.female, 78, 77)
addVariation(Variations.Visor.female, 79, 80)
addVariation(Variations.Visor.female, 18, 66)
addVariation(Variations.Visor.female, 66, 81)
addVariation(Variations.Visor.female, 81, 66)
addVariation(Variations.Visor.female, 86, 84)
addVariation(Variations.Visor.female, 90, 91)
addVariation(Variations.Visor.female, 103, 104)
addVariation(Variations.Visor.female, 108, 109)
addVariation(Variations.Visor.female, 115, 116)
addVariation(Variations.Visor.female, 117, 118)
addVariation(Variations.Visor.female, 122, 123)
addVariation(Variations.Visor.female, 124, 125)
addVariation(Variations.Visor.female, 126, 127)
addVariation(Variations.Visor.female, 129, 130)
-- [[ Hair ]] --
-- MALE
addVariation(Variations.Hair.male, 7, 15, true)
addVariation(Variations.Hair.male, 43, 15, true)
addVariation(Variations.Hair.male, 9, 43, true)
addVariation(Variations.Hair.male, 11, 43, true)
addVariation(Variations.Hair.male, 15, 43, true)
addVariation(Variations.Hair.male, 16, 43, true)
addVariation(Variations.Hair.male, 17, 43, true)
addVariation(Variations.Hair.male, 20, 43, true)
addVariation(Variations.Hair.male, 22, 43, true)
addVariation(Variations.Hair.male, 45, 43, true)
addVariation(Variations.Hair.male, 47, 43, true)
addVariation(Variations.Hair.male, 49, 43, true)
addVariation(Variations.Hair.male, 51, 43, true)
addVariation(Variations.Hair.male, 52, 43, true)
addVariation(Variations.Hair.male, 53, 43, true)
addVariation(Variations.Hair.male, 56, 43, true)
addVariation(Variations.Hair.male, 58, 43, true)
-- FEMALE
addVariation(Variations.Hair.female, 1, 49, true)
addVariation(Variations.Hair.female, 2, 49, true)
addVariation(Variations.Hair.female, 7, 49, true)
addVariation(Variations.Hair.female, 9, 49, true)
addVariation(Variations.Hair.female, 10, 49, true)
addVariation(Variations.Hair.female, 11, 48, true)
addVariation(Variations.Hair.female, 14, 53, true)
addVariation(Variations.Hair.female, 15, 42, true)
addVariation(Variations.Hair.female, 21, 42, true)
addVariation(Variations.Hair.female, 23, 42, true)
addVariation(Variations.Hair.female, 31, 53, true)
addVariation(Variations.Hair.female, 39, 49, true)
addVariation(Variations.Hair.female, 40, 49, true)
addVariation(Variations.Hair.female, 42, 53, true)
addVariation(Variations.Hair.female, 45, 49, true)
addVariation(Variations.Hair.female, 48, 49, true)
addVariation(Variations.Hair.female, 49, 48, true)
addVariation(Variations.Hair.female, 52, 53, true)
addVariation(Variations.Hair.female, 53, 42, true)
addVariation(Variations.Hair.female, 54, 55, true)
addVariation(Variations.Hair.female, 59, 42, true)
addVariation(Variations.Hair.female, 59, 54, true)
addVariation(Variations.Hair.female, 68, 53, true)
addVariation(Variations.Hair.female, 76, 48, true)
-- [[ Gloves ]] --
-- MALE
addVariation(Variations.Gloves.male, 16, 4, true)
addVariation(Variations.Gloves.male, 17, 4, true)
addVariation(Variations.Gloves.male, 18, 4, true)
addVariation(Variations.Gloves.male, 19, 0, true)
addVariation(Variations.Gloves.male, 20, 1, true)
addVariation(Variations.Gloves.male, 21, 2, true)
addVariation(Variations.Gloves.male, 22, 4, true)
addVariation(Variations.Gloves.male, 23, 5, true)
addVariation(Variations.Gloves.male, 24, 6, true)
addVariation(Variations.Gloves.male, 25, 8, true)
addVariation(Variations.Gloves.male, 26, 11, true)
addVariation(Variations.Gloves.male, 27, 12, true)
addVariation(Variations.Gloves.male, 28, 14, true)
addVariation(Variations.Gloves.male, 29, 15, true)
addVariation(Variations.Gloves.male, 30, 0, true)
addVariation(Variations.Gloves.male, 31, 1, true)
addVariation(Variations.Gloves.male, 32, 2, true)
addVariation(Variations.Gloves.male, 33, 4, true)
addVariation(Variations.Gloves.male, 34, 5, true)
addVariation(Variations.Gloves.male, 35, 6, true)
addVariation(Variations.Gloves.male, 36, 8, true)
addVariation(Variations.Gloves.male, 37, 11, true)
addVariation(Variations.Gloves.male, 38, 12, true)
addVariation(Variations.Gloves.male, 39, 14, true)
addVariation(Variations.Gloves.male, 40, 15, true)
addVariation(Variations.Gloves.male, 41, 0, true)
addVariation(Variations.Gloves.male, 42, 1, true)
addVariation(Variations.Gloves.male, 43, 2, true)
addVariation(Variations.Gloves.male, 44, 4, true)
addVariation(Variations.Gloves.male, 45, 5, true)
addVariation(Variations.Gloves.male, 46, 6, true)
addVariation(Variations.Gloves.male, 47, 8, true)
addVariation(Variations.Gloves.male, 48, 11, true)
addVariation(Variations.Gloves.male, 49, 12, true)
addVariation(Variations.Gloves.male, 50, 14, true)
addVariation(Variations.Gloves.male, 51, 15, true)
addVariation(Variations.Gloves.male, 52, 0, true)
addVariation(Variations.Gloves.male, 53, 1, true)
addVariation(Variations.Gloves.male, 54, 2, true)
addVariation(Variations.Gloves.male, 55, 4, true)
addVariation(Variations.Gloves.male, 56, 5, true)
addVariation(Variations.Gloves.male, 57, 6, true)
addVariation(Variations.Gloves.male, 58, 8, true)
addVariation(Variations.Gloves.male, 59, 11, true)
addVariation(Variations.Gloves.male, 60, 12, true)
addVariation(Variations.Gloves.male, 61, 14, true)
addVariation(Variations.Gloves.male, 62, 15, true)
addVariation(Variations.Gloves.male, 63, 0, true)
addVariation(Variations.Gloves.male, 64, 1, true)
addVariation(Variations.Gloves.male, 65, 2, true)
addVariation(Variations.Gloves.male, 66, 4, true)
addVariation(Variations.Gloves.male, 67, 5, true)
addVariation(Variations.Gloves.male, 68, 6, true)
addVariation(Variations.Gloves.male, 69, 8, true)
addVariation(Variations.Gloves.male, 70, 11, true)
addVariation(Variations.Gloves.male, 71, 12, true)
addVariation(Variations.Gloves.male, 72, 14, true)
addVariation(Variations.Gloves.male, 73, 15, true)
addVariation(Variations.Gloves.male, 74, 0, true)
addVariation(Variations.Gloves.male, 75, 1, true)
addVariation(Variations.Gloves.male, 76, 2, true)
addVariation(Variations.Gloves.male, 77, 4, true)
addVariation(Variations.Gloves.male, 78, 5, true)
addVariation(Variations.Gloves.male, 79, 6, true)
addVariation(Variations.Gloves.male, 80, 8, true)
addVariation(Variations.Gloves.male, 81, 11, true)
addVariation(Variations.Gloves.male, 82, 12, true)
addVariation(Variations.Gloves.male, 83, 14, true)
addVariation(Variations.Gloves.male, 84, 15, true)
addVariation(Variations.Gloves.male, 85, 0, true)
addVariation(Variations.Gloves.male, 86, 1, true)
addVariation(Variations.Gloves.male, 87, 2, true)
addVariation(Variations.Gloves.male, 88, 4, true)
addVariation(Variations.Gloves.male, 89, 5, true)
addVariation(Variations.Gloves.male, 90, 6, true)
addVariation(Variations.Gloves.male, 91, 8, true)
addVariation(Variations.Gloves.male, 92, 11, true)
addVariation(Variations.Gloves.male, 93, 12, true)
addVariation(Variations.Gloves.male, 94, 14, true)
addVariation(Variations.Gloves.male, 95, 15, true)
addVariation(Variations.Gloves.male, 96, 4, true)
addVariation(Variations.Gloves.male, 97, 4, true)
addVariation(Variations.Gloves.male, 98, 4, true)
addVariation(Variations.Gloves.male, 99, 0, true)
addVariation(Variations.Gloves.male, 100, 1, true)
addVariation(Variations.Gloves.male, 101, 2, true)
addVariation(Variations.Gloves.male, 102, 4, true)
addVariation(Variations.Gloves.male, 103, 5, true)
addVariation(Variations.Gloves.male, 104, 6, true)
addVariation(Variations.Gloves.male, 105, 8, true)
addVariation(Variations.Gloves.male, 106, 11, true)
addVariation(Variations.Gloves.male, 107, 12, true)
addVariation(Variations.Gloves.male, 108, 14, true)
addVariation(Variations.Gloves.male, 109, 15, true)
addVariation(Variations.Gloves.male, 110, 4, true)
addVariation(Variations.Gloves.male, 111, 4, true)
addVariation(Variations.Gloves.male, 115, 112, true)
addVariation(Variations.Gloves.male, 116, 112, true)
addVariation(Variations.Gloves.male, 117, 112, true)
addVariation(Variations.Gloves.male, 118, 112, true)
addVariation(Variations.Gloves.male, 119, 112, true)
addVariation(Variations.Gloves.male, 120, 112, true)
addVariation(Variations.Gloves.male, 121, 112, true)
addVariation(Variations.Gloves.male, 122, 113, true)
addVariation(Variations.Gloves.male, 123, 113, true)
addVariation(Variations.Gloves.male, 124, 113, true)
addVariation(Variations.Gloves.male, 125, 113, true)
addVariation(Variations.Gloves.male, 126, 113, true)
addVariation(Variations.Gloves.male, 127, 113, true)
addVariation(Variations.Gloves.male, 128, 113, true)
addVariation(Variations.Gloves.male, 129, 114, true)
addVariation(Variations.Gloves.male, 130, 114, true)
addVariation(Variations.Gloves.male, 131, 114, true)
addVariation(Variations.Gloves.male, 132, 114, true)
addVariation(Variations.Gloves.male, 133, 114, true)
addVariation(Variations.Gloves.male, 134, 114, true)
addVariation(Variations.Gloves.male, 135, 114, true)
addVariation(Variations.Gloves.male, 136, 15, true)
addVariation(Variations.Gloves.male, 137, 15, true)
addVariation(Variations.Gloves.male, 138, 0, true)
addVariation(Variations.Gloves.male, 139, 1, true)
addVariation(Variations.Gloves.male, 140, 2, true)
addVariation(Variations.Gloves.male, 141, 4, true)
addVariation(Variations.Gloves.male, 142, 5, true)
addVariation(Variations.Gloves.male, 143, 6, true)
addVariation(Variations.Gloves.male, 144, 8, true)
addVariation(Variations.Gloves.male, 145, 11, true)
addVariation(Variations.Gloves.male, 146, 12, true)
addVariation(Variations.Gloves.male, 147, 14, true)
addVariation(Variations.Gloves.male, 148, 112, true)
addVariation(Variations.Gloves.male, 149, 113, true)
addVariation(Variations.Gloves.male, 150, 114, true)
addVariation(Variations.Gloves.male, 151, 0, true)
addVariation(Variations.Gloves.male, 152, 1, true)
addVariation(Variations.Gloves.male, 153, 2, true)
addVariation(Variations.Gloves.male, 154, 4, true)
addVariation(Variations.Gloves.male, 155, 5, true)
addVariation(Variations.Gloves.male, 156, 6, true)
addVariation(Variations.Gloves.male, 157, 8, true)
addVariation(Variations.Gloves.male, 158, 11, true)
addVariation(Variations.Gloves.male, 159, 12, true)
addVariation(Variations.Gloves.male, 160, 14, true)
addVariation(Variations.Gloves.male, 161, 112, true)
addVariation(Variations.Gloves.male, 162, 113, true)
addVariation(Variations.Gloves.male, 163, 114, true)
addVariation(Variations.Gloves.male, 165, 4, true)
addVariation(Variations.Gloves.male, 166, 4, true)
addVariation(Variations.Gloves.male, 167, 4, true)
-- FEMALE
addVariation(Variations.Gloves.female, 16, 11, true)
addVariation(Variations.Gloves.female, 17, 3, true)
addVariation(Variations.Gloves.female, 18, 3, true)
addVariation(Variations.Gloves.female, 19, 3, true)
addVariation(Variations.Gloves.female, 20, 0, true)
addVariation(Variations.Gloves.female, 21, 1, true)
addVariation(Variations.Gloves.female, 22, 2, true)
addVariation(Variations.Gloves.female, 23, 3, true)
addVariation(Variations.Gloves.female, 24, 4, true)
addVariation(Variations.Gloves.female, 25, 5, true)
addVariation(Variations.Gloves.female, 26, 6, true)
addVariation(Variations.Gloves.female, 27, 7, true)
addVariation(Variations.Gloves.female, 28, 9, true)
addVariation(Variations.Gloves.female, 29, 11, true)
addVariation(Variations.Gloves.female, 30, 12, true)
addVariation(Variations.Gloves.female, 31, 14, true)
addVariation(Variations.Gloves.female, 32, 15, true)
addVariation(Variations.Gloves.female, 33, 0, true)
addVariation(Variations.Gloves.female, 34, 1, true)
addVariation(Variations.Gloves.female, 35, 2, true)
addVariation(Variations.Gloves.female, 36, 3, true)
addVariation(Variations.Gloves.female, 37, 4, true)
addVariation(Variations.Gloves.female, 38, 5, true)
addVariation(Variations.Gloves.female, 39, 6, true)
addVariation(Variations.Gloves.female, 40, 7, true)
addVariation(Variations.Gloves.female, 41, 9, true)
addVariation(Variations.Gloves.female, 42, 11, true)
addVariation(Variations.Gloves.female, 43, 12, true)
addVariation(Variations.Gloves.female, 44, 14, true)
addVariation(Variations.Gloves.female, 45, 15, true)
addVariation(Variations.Gloves.female, 46, 0, true)
addVariation(Variations.Gloves.female, 47, 1, true)
addVariation(Variations.Gloves.female, 48, 2, true)
addVariation(Variations.Gloves.female, 49, 3, true)
addVariation(Variations.Gloves.female, 50, 4, true)
addVariation(Variations.Gloves.female, 51, 5, true)
addVariation(Variations.Gloves.female, 52, 6, true)
addVariation(Variations.Gloves.female, 53, 7, true)
addVariation(Variations.Gloves.female, 54, 9, true)
addVariation(Variations.Gloves.female, 55, 11, true)
addVariation(Variations.Gloves.female, 56, 12, true)
addVariation(Variations.Gloves.female, 57, 14, true)
addVariation(Variations.Gloves.female, 58, 15, true)
addVariation(Variations.Gloves.female, 59, 0, true)
addVariation(Variations.Gloves.female, 60, 1, true)
addVariation(Variations.Gloves.female, 61, 2, true)
addVariation(Variations.Gloves.female, 62, 3, true)
addVariation(Variations.Gloves.female, 63, 4, true)
addVariation(Variations.Gloves.female, 64, 5, true)
addVariation(Variations.Gloves.female, 65, 6, true)
addVariation(Variations.Gloves.female, 66, 7, true)
addVariation(Variations.Gloves.female, 67, 9, true)
addVariation(Variations.Gloves.female, 68, 11, true)
addVariation(Variations.Gloves.female, 69, 12, true)
addVariation(Variations.Gloves.female, 70, 14, true)
addVariation(Variations.Gloves.female, 71, 15, true)
addVariation(Variations.Gloves.female, 72, 0, true)
addVariation(Variations.Gloves.female, 73, 1, true)
addVariation(Variations.Gloves.female, 74, 2, true)
addVariation(Variations.Gloves.female, 75, 3, true)
addVariation(Variations.Gloves.female, 76, 4, true)
addVariation(Variations.Gloves.female, 77, 5, true)
addVariation(Variations.Gloves.female, 78, 6, true)
addVariation(Variations.Gloves.female, 79, 7, true)
addVariation(Variations.Gloves.female, 80, 9, true)
addVariation(Variations.Gloves.female, 81, 11, true)
addVariation(Variations.Gloves.female, 82, 12, true)
addVariation(Variations.Gloves.female, 83, 14, true)
addVariation(Variations.Gloves.female, 84, 15, true)
addVariation(Variations.Gloves.female, 85, 0, true)
addVariation(Variations.Gloves.female, 86, 1, true)
addVariation(Variations.Gloves.female, 87, 2, true)
addVariation(Variations.Gloves.female, 88, 3, true)
addVariation(Variations.Gloves.female, 89, 4, true)
addVariation(Variations.Gloves.female, 90, 5, true)
addVariation(Variations.Gloves.female, 91, 6, true)
addVariation(Variations.Gloves.female, 92, 7, true)
addVariation(Variations.Gloves.female, 93, 9, true)
addVariation(Variations.Gloves.female, 94, 11, true)
addVariation(Variations.Gloves.female, 95, 12, true)
addVariation(Variations.Gloves.female, 96, 14, true)
addVariation(Variations.Gloves.female, 97, 15, true)
addVariation(Variations.Gloves.female, 98, 0, true)
addVariation(Variations.Gloves.female, 99, 1, true)
addVariation(Variations.Gloves.female, 100, 2, true)
addVariation(Variations.Gloves.female, 101, 3, true)
addVariation(Variations.Gloves.female, 102, 4, true)
addVariation(Variations.Gloves.female, 103, 5, true)
addVariation(Variations.Gloves.female, 104, 6, true)
addVariation(Variations.Gloves.female, 105, 7, true)
addVariation(Variations.Gloves.female, 106, 9, true)
addVariation(Variations.Gloves.female, 107, 11, true)
addVariation(Variations.Gloves.female, 108, 12, true)
addVariation(Variations.Gloves.female, 109, 14, true)
addVariation(Variations.Gloves.female, 110, 15, true)
addVariation(Variations.Gloves.female, 111, 3, true)
addVariation(Variations.Gloves.female, 112, 3, true)
addVariation(Variations.Gloves.female, 113, 3, true)
addVariation(Variations.Gloves.female, 114, 0, true)
addVariation(Variations.Gloves.female, 115, 1, true)
addVariation(Variations.Gloves.female, 116, 2, true)
addVariation(Variations.Gloves.female, 117, 3, true)
addVariation(Variations.Gloves.female, 118, 4, true)
addVariation(Variations.Gloves.female, 119, 5, true)
addVariation(Variations.Gloves.female, 120, 6, true)
addVariation(Variations.Gloves.female, 121, 7, true)
addVariation(Variations.Gloves.female, 122, 9, true)
addVariation(Variations.Gloves.female, 123, 11, true)
addVariation(Variations.Gloves.female, 124, 12, true)
addVariation(Variations.Gloves.female, 125, 14, true)
addVariation(Variations.Gloves.female, 126, 15, true)
addVariation(Variations.Gloves.female, 127, 3, true)
addVariation(Variations.Gloves.female, 128, 3, true)
addVariation(Variations.Gloves.female, 132, 129, true)
addVariation(Variations.Gloves.female, 133, 129, true)
addVariation(Variations.Gloves.female, 134, 129, true)
addVariation(Variations.Gloves.female, 135, 129, true)
addVariation(Variations.Gloves.female, 136, 129, true)
addVariation(Variations.Gloves.female, 137, 129, true)
addVariation(Variations.Gloves.female, 138, 129, true)
addVariation(Variations.Gloves.female, 139, 130, true)
addVariation(Variations.Gloves.female, 140, 130, true)
addVariation(Variations.Gloves.female, 141, 130, true)
addVariation(Variations.Gloves.female, 142, 130, true)
addVariation(Variations.Gloves.female, 143, 130, true)
addVariation(Variations.Gloves.female, 144, 130, true)
addVariation(Variations.Gloves.female, 145, 130, true)
addVariation(Variations.Gloves.female, 146, 131, true)
addVariation(Variations.Gloves.female, 147, 131, true)
addVariation(Variations.Gloves.female, 148, 131, true)
addVariation(Variations.Gloves.female, 149, 131, true)
addVariation(Variations.Gloves.female, 150, 131, true)
addVariation(Variations.Gloves.female, 151, 131, true)
addVariation(Variations.Gloves.female, 152, 131, true)
addVariation(Variations.Gloves.female, 154, 153, true)
addVariation(Variations.Gloves.female, 155, 153, true)
addVariation(Variations.Gloves.female, 156, 153, true)
addVariation(Variations.Gloves.female, 157, 153, true)
addVariation(Variations.Gloves.female, 158, 153, true)
addVariation(Variations.Gloves.female, 159, 153, true)
addVariation(Variations.Gloves.female, 160, 153, true)
addVariation(Variations.Gloves.female, 162, 161, true)
addVariation(Variations.Gloves.female, 163, 161, true)
addVariation(Variations.Gloves.female, 164, 161, true)
addVariation(Variations.Gloves.female, 165, 161, true)
addVariation(Variations.Gloves.female, 166, 161, true)
addVariation(Variations.Gloves.female, 167, 161, true)
addVariation(Variations.Gloves.female, 168, 161, true)
addVariation(Variations.Gloves.female, 169, 15, true)
addVariation(Variations.Gloves.female, 170, 15, true)
addVariation(Variations.Gloves.female, 171, 0, true)
addVariation(Variations.Gloves.female, 172, 1, true)
addVariation(Variations.Gloves.female, 173, 2, true)
addVariation(Variations.Gloves.female, 174, 3, true)
addVariation(Variations.Gloves.female, 175, 4, true)
addVariation(Variations.Gloves.female, 176, 5, true)
addVariation(Variations.Gloves.female, 177, 6, true)
addVariation(Variations.Gloves.female, 178, 7, true)
addVariation(Variations.Gloves.female, 179, 9, true)
addVariation(Variations.Gloves.female, 180, 11, true)
addVariation(Variations.Gloves.female, 181, 12, true)
addVariation(Variations.Gloves.female, 182, 14, true)
addVariation(Variations.Gloves.female, 183, 129, true)
addVariation(Variations.Gloves.female, 184, 130, true)
addVariation(Variations.Gloves.female, 185, 131, true)
addVariation(Variations.Gloves.female, 186, 153, true)
addVariation(Variations.Gloves.female, 187, 0, true)
addVariation(Variations.Gloves.female, 188, 1, true)
addVariation(Variations.Gloves.female, 189, 2, true)
addVariation(Variations.Gloves.female, 190, 3, true)
addVariation(Variations.Gloves.female, 191, 4, true)
addVariation(Variations.Gloves.female, 192, 5, true)
addVariation(Variations.Gloves.female, 193, 6, true)
addVariation(Variations.Gloves.female, 194, 7, true)
addVariation(Variations.Gloves.female, 195, 9, true)
addVariation(Variations.Gloves.female, 196, 11, true)
addVariation(Variations.Gloves.female, 197, 12, true)
addVariation(Variations.Gloves.female, 198, 14, true)
addVariation(Variations.Gloves.female, 199, 129, true)
addVariation(Variations.Gloves.female, 200, 130, true)
addVariation(Variations.Gloves.female, 201, 131, true)
addVariation(Variations.Gloves.female, 202, 153, true)
addVariation(Variations.Gloves.female, 203, 161, true)
addVariation(Variations.Gloves.female, 204, 161, true)
addVariation(Variations.Gloves.female, 206, 3, true)
addVariation(Variations.Gloves.female, 207, 3, true)
addVariation(Variations.Gloves.female, 208, 3, true)
